
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import ClerkContainer from "@/app/Utils/ClerkProviderContainer";
import Navbar from "@/app/Utils/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "./Utils/ThemeProvider";
import { Menu } from 'lucide-react';
import 'regenerator-runtime/runtime';
// import { useState } from "react";
const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={poppins.className}  suppressHydrationWarning={true} >
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        >
          <ClerkContainer>
            <div className="min-h-screen grid grid-cols-1 md:grid-cols-11 justify-center" >
           <Navbar />
             
              <div className="col-span-9 py-9 px-6 md:p-10">
                
                <Toaster />
                {children}
              </div>
            </div>
            
          </ClerkContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
